import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import yaml from 'js-yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Generate Terraform tfvars content from cluster configuration
 */
function generateTerraformVars(deployment) {
  const { clusterConfig, cloudProvider } = deployment;
  const { name, region, vpc, subnet, nodePools } = clusterConfig;

  // Extract region and availability zone
  let awsRegion = region || 'us-east-1';
  let availabilityZone = `${awsRegion}a`;
  
  // Handle full region string like "us-east-1a"
  if (region && region.includes('-') && region.match(/[a-z]$/)) {
    availabilityZone = region;
    awsRegion = region.slice(0, -1);
  }

  // Convert nodePools to worker_instances format
  const workerInstances = {};
  const poolEnvVars = {};
  if (nodePools && nodePools.length > 0) {
    nodePools.forEach((pool, poolIndex) => {
      if (pool.machines && pool.machines.length > 0) {
        pool.machines.forEach((machine, machineIndex) => {
          const groupName = `group-${poolIndex + 1}-${machineIndex + 1}`;
          workerInstances[groupName] = {
            type: machine.machineType,
            count: machine.nodeCount || 1
          };
        });
      }
      // Collect per-pool env vars
      if (pool.envVars && pool.envVars.length > 0) {
        const envObj = {};
        for (const ev of pool.envVars) {
          if (ev.key && ev.key.trim()) {
            envObj[ev.key] = ev.value || '';
          }
        }
        if (Object.keys(envObj).length > 0) {
          poolEnvVars[pool.name || `pool-${poolIndex + 1}`] = envObj;
        }
      }
    });
  }

  // Build tfvars content
  let tfvars = `# Auto-generated by Ascendra Installer
# Generated at: ${new Date().toISOString()}

cluster_name         = "${name}"
aws_region           = "${awsRegion}"
availability_zone    = "${availabilityZone}"
master_instance_type = "t3.large"
ssh_public_key       = ""

# Network Configuration
# If vpc_id and subnet_id are provided, they will be used.
# Otherwise, new VPC and subnet will be created with the specified CIDR blocks.
vpc_id      = "${vpc || ''}"
subnet_id   = "${subnet || ''}"
vpc_cidr    = "10.0.0.0/16"
subnet_cidr = "10.0.1.0/24"

# Worker node configuration
`;

  // Add worker_instances in HCL format
  if (Object.keys(workerInstances).length > 0) {
    tfvars += 'worker_instances = {\n';
    for (const [groupName, config] of Object.entries(workerInstances)) {
      tfvars += `  "${groupName}" = {\n`;
      tfvars += `    type  = "${config.type}"\n`;
      tfvars += `    count = ${config.count}\n`;
      tfvars += `  }\n`;
    }
    tfvars += '}\n';
  } else {
    tfvars += 'worker_instances = {}\n';
  }

  // Add cluster-wide environment variables
  const clusterEnvVars = clusterConfig.envVars;
  if (clusterEnvVars && Array.isArray(clusterEnvVars) && clusterEnvVars.length > 0) {
    tfvars += '\n# Cluster-wide environment variables\ncluster_env_vars = {\n';
    for (const ev of clusterEnvVars) {
      if (ev.key && ev.key.trim()) {
        tfvars += `  "${ev.key}" = "${(ev.value || '').replace(/"/g, '\\"')}"\n`;
      }
    }
    tfvars += '}\n';
  }

  // Add per-pool environment variables
  if (Object.keys(poolEnvVars).length > 0) {
    tfvars += '\n# Per-pool environment variables\npool_env_vars = {\n';
    for (const [poolName, envObj] of Object.entries(poolEnvVars)) {
      tfvars += `  "${poolName}" = {\n`;
      for (const [key, value] of Object.entries(envObj)) {
        tfvars += `    "${key}" = "${String(value).replace(/"/g, '\\"')}"\n`;
      }
      tfvars += `  }\n`;
    }
    tfvars += '}\n';
  }

  return tfvars;
}

/**
 * Update Ansible group_vars/all.yml with component selections
 */
function generateAnsibleVars(deployment) {
  const { selectedComponents } = deployment;
  
  // Read existing all.yml
  const projectRoot = path.resolve(__dirname, process.env.PROJECT_ROOT || '../../../');
  const allYmlPath = path.join(projectRoot, 'ansible/group_vars/all.yml');
  
  let allYmlContent = {};
  if (fs.existsSync(allYmlPath)) {
    const content = fs.readFileSync(allYmlPath, 'utf8');
    allYmlContent = yaml.load(content) || {};
  }

  // Detect OS types from individual nodes (per-node osType)
  const onPremConfig = deployment.onPremiseConfig;
  if (onPremConfig) {
    const allNodes = [
      ...(onPremConfig.controlPlane?.nodes || []),
      ...(onPremConfig.workerNodes || []).flatMap(g => g.nodes || [])
    ];
    const hasSuse = allNodes.some(n => n.osType === 'suse');
    const hasUbuntu = allNodes.some(n => n.osType !== 'suse');
    if (hasSuse && hasUbuntu) {
      allYmlContent.os_type = 'mixed';
    } else if (hasSuse) {
      allYmlContent.os_type = 'suse';
    } else {
      allYmlContent.os_type = 'ubuntu';
    }
  }

  // Add cluster-wide environment variables from config
  const envVars = deployment.clusterConfig?.envVars || deployment.onPremiseConfig?.envVars;
  if (envVars && Array.isArray(envVars) && envVars.length > 0) {
    const envObj = {};
    for (const ev of envVars) {
      if (ev.key && ev.key.trim()) {
        envObj[ev.key] = ev.value || '';
      }
    }
    if (Object.keys(envObj).length > 0) {
      allYmlContent.cluster_env_vars = envObj;
    }
  }

  // Update Tyr configuration if backend-api is selected
  if (selectedComponents && selectedComponents['backend-api']) {
    if (!allYmlContent.tyr_ghcr_username) {
      allYmlContent.tyr_ghcr_username = process.env.TYR_GHCR_USERNAME || 'avivl777';
    }
    if (!allYmlContent.tyr_ghcr_password) {
      allYmlContent.tyr_ghcr_password = process.env.TYR_GHCR_PASSWORD || '';
    }
    if (!allYmlContent.tyr_version) {
      allYmlContent.tyr_version = process.env.TYR_VERSION || '1.0.4';
    }
  }

  // Update Dashboard configuration if dashboard is selected
  if (selectedComponents && selectedComponents['dashboard']) {
    if (!allYmlContent.tyr_ghcr_username) {
      allYmlContent.tyr_ghcr_username = process.env.TYR_GHCR_USERNAME || 'avivl777';
    }
    if (!allYmlContent.tyr_ghcr_password) {
      allYmlContent.tyr_ghcr_password = process.env.TYR_GHCR_PASSWORD || '';
    }
    if (!allYmlContent.dashboard_version) {
      allYmlContent.dashboard_version = process.env.DASHBOARD_VERSION || '1.0.26';
    }
  }

  return yaml.dump(allYmlContent, { indent: 2, lineWidth: -1 });
}

/**
 * Write Terraform tfvars file
 */
function writeTerraformVars(deployment, tfvarsContent) {
  const projectRoot = path.resolve(__dirname, process.env.PROJECT_ROOT || '../../../');
  const envDir = path.join(projectRoot, process.env.TERRAFORM_ENV_DIR || 'terraform/environments/aws-dev');
  const tfvarsPath = path.join(envDir, `${deployment.clusterConfig.name}.tfvars`);
  
  // Ensure directory exists
  if (!fs.existsSync(envDir)) {
    fs.mkdirSync(envDir, { recursive: true });
  }
  
  fs.writeFileSync(tfvarsPath, tfvarsContent);
  console.log(`[ConfigGenerator] Written tfvars to: ${tfvarsPath}`);
  
  return tfvarsPath;
}

/**
 * Write Ansible variables file to both group_vars locations
 * so Ansible finds them regardless of inventory/playbook resolution
 */
function writeAnsibleVars(ansibleVarsContent) {
  const projectRoot = path.resolve(__dirname, process.env.PROJECT_ROOT || '../../../');
  const allYmlPath = path.join(projectRoot, 'ansible/group_vars/all.yml');
  const inventoryGroupVarsDir = path.join(projectRoot, 'ansible/inventory/group_vars');
  const inventoryAllYmlPath = path.join(inventoryGroupVarsDir, 'all.yml');
  
  // Backup existing file
  if (fs.existsSync(allYmlPath)) {
    const backupPath = `${allYmlPath}.backup-${Date.now()}`;
    fs.copyFileSync(allYmlPath, backupPath);
    console.log(`[ConfigGenerator] Backed up existing all.yml to: ${backupPath}`);
  }
  
  fs.writeFileSync(allYmlPath, ansibleVarsContent);
  console.log(`[ConfigGenerator] Written Ansible vars to: ${allYmlPath}`);

  // Also write to inventory/group_vars/ for directory-based inventory resolution
  if (!fs.existsSync(inventoryGroupVarsDir)) {
    fs.mkdirSync(inventoryGroupVarsDir, { recursive: true });
  }
  fs.writeFileSync(inventoryAllYmlPath, ansibleVarsContent);
  console.log(`[ConfigGenerator] Written Ansible vars to: ${inventoryAllYmlPath}`);

  // Copy masters.yml and workers.yml into inventory group_vars too
  const groupVarsDir = path.join(projectRoot, 'ansible/group_vars');
  for (const groupFile of ['masters.yml', 'workers.yml']) {
    const src = path.join(groupVarsDir, groupFile);
    const dest = path.join(inventoryGroupVarsDir, groupFile);
    if (fs.existsSync(src)) {
      fs.copyFileSync(src, dest);
    }
  }
  
  return allYmlPath;
}

/**
 * Generate configuration for on-premise deployments
 */
function generateOnPremiseConfig(deployment) {
  // For on-premise, we only need Ansible vars, no Terraform
  const ansibleVarsContent = generateAnsibleVars(deployment);
  const ansibleVarsPath = writeAnsibleVars(ansibleVarsContent);
  
  return {
    ansibleVarsPath,
    ansibleVarsContent
  };
}

/**
 * Generate all configuration files for deployment
 */
function generateConfigurations(deployment) {
  const { cloudProvider } = deployment;
  
  // For on-premise deployments, skip Terraform configuration
  if (cloudProvider === 'on-premise' || cloudProvider === 'onpremise') {
    return generateOnPremiseConfig(deployment);
  }
  
  // For cloud deployments (AWS, etc.), generate both Terraform and Ansible configs
  const tfvarsContent = generateTerraformVars(deployment);
  const ansibleVarsContent = generateAnsibleVars(deployment);
  
  const tfvarsPath = writeTerraformVars(deployment, tfvarsContent);
  const ansibleVarsPath = writeAnsibleVars(ansibleVarsContent);
  
  return {
    tfvarsPath,
    ansibleVarsPath,
    tfvarsContent,
    ansibleVarsContent
  };
}

export {
  generateTerraformVars,
  generateAnsibleVars,
  writeTerraformVars,
  writeAnsibleVars,
  generateOnPremiseConfig,
  generateConfigurations
};

