import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import yaml from 'js-yaml';
import defaultsService from './defaults.service.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Generate Terraform tfvars content from cluster configuration
 */
function generateTerraformVars(deployment) {
  const { clusterConfig, cloudProvider } = deployment;
  const { name, region, vpc, subnet, nodePools } = clusterConfig;

  // Extract region and availability zone
  let awsRegion = region || 'us-east-1';
  let availabilityZone = `${awsRegion}a`;
  
  // Handle full region string like "us-east-1a"
  if (region && region.includes('-') && region.match(/[a-z]$/)) {
    availabilityZone = region;
    awsRegion = region.slice(0, -1);
  }

  // Convert nodePools to worker_instances format
  const workerInstances = {};
  const poolEnvVars = {};
  if (nodePools && nodePools.length > 0) {
    nodePools.forEach((pool, poolIndex) => {
      if (pool.machines && pool.machines.length > 0) {
        pool.machines.forEach((machine, machineIndex) => {
          const groupName = `group-${poolIndex + 1}-${machineIndex + 1}`;
          workerInstances[groupName] = {
            type: machine.machineType,
            count: machine.nodeCount || 1
          };
        });
      }
      // Collect per-pool env vars
      if (pool.envVars && pool.envVars.length > 0) {
        const envObj = {};
        for (const ev of pool.envVars) {
          if (ev.key && ev.key.trim()) {
            envObj[ev.key] = ev.value || '';
          }
        }
        if (Object.keys(envObj).length > 0) {
          poolEnvVars[pool.name || `pool-${poolIndex + 1}`] = envObj;
        }
      }
    });
  }

  // Build tfvars content
  let tfvars = `# Auto-generated by Ascendra Installer
# Generated at: ${new Date().toISOString()}

cluster_name         = "${name}"
aws_region           = "${awsRegion}"
availability_zone    = "${availabilityZone}"
master_instance_type = "${defaultsService.defaults?.compute?.master?.instanceType || 't3.xlarge'}"
ssh_public_key       = ""

# Network Configuration
# If vpc_id and subnet_id are provided, they will be used.
# Otherwise, new VPC and subnet will be created with the specified CIDR blocks.
vpc_id      = "${vpc || ''}"
subnet_id   = "${subnet || ''}"
vpc_cidr    = "10.0.0.0/16"
subnet_cidr = "10.0.1.0/24"

# Worker node configuration
`;

  // Add worker_instances in HCL format
  if (Object.keys(workerInstances).length > 0) {
    tfvars += 'worker_instances = {\n';
    for (const [groupName, config] of Object.entries(workerInstances)) {
      tfvars += `  "${groupName}" = {\n`;
      tfvars += `    type  = "${config.type}"\n`;
      tfvars += `    count = ${config.count}\n`;
      tfvars += `  }\n`;
    }
    tfvars += '}\n';
  } else {
    tfvars += 'worker_instances = {}\n';
  }

  // Add cluster-wide environment variables
  const clusterEnvVars = clusterConfig.envVars;
  if (clusterEnvVars && Array.isArray(clusterEnvVars) && clusterEnvVars.length > 0) {
    tfvars += '\n# Cluster-wide environment variables\ncluster_env_vars = {\n';
    for (const ev of clusterEnvVars) {
      if (ev.key && ev.key.trim()) {
        tfvars += `  "${ev.key}" = "${(ev.value || '').replace(/"/g, '\\"')}"\n`;
      }
    }
    tfvars += '}\n';
  }

  // Add per-pool environment variables
  if (Object.keys(poolEnvVars).length > 0) {
    tfvars += '\n# Per-pool environment variables\npool_env_vars = {\n';
    for (const [poolName, envObj] of Object.entries(poolEnvVars)) {
      tfvars += `  "${poolName}" = {\n`;
      for (const [key, value] of Object.entries(envObj)) {
        tfvars += `    "${key}" = "${String(value).replace(/"/g, '\\"')}"\n`;
      }
      tfvars += `  }\n`;
    }
    tfvars += '}\n';
  }

  return tfvars;
}

/**
 * Build a sensible NO_PROXY value from the cluster's internal CIDRs.
 * These addresses must never go through the proxy — if they do, control-plane
 * components (kubelet → kube-apiserver, etc.) will fail to connect internally.
 *
 *   localhost / loopback
 *   pod_network_cidr      (kubeadm --pod-network-cidr, default 10.10.0.0/16)
 *   service_cidr          (kubeadm --service-cidr, default 10.96.0.0/12)
 *   .svc / .cluster.local (in-cluster DNS suffixes)
 *   All three RFC 1918 private ranges — covers node gateways on any typical
 *   network (10.x.x.x for AWS, 172.16-31.x.x for some DCs, 192.168.x.x for
 *   on-premise). Without 172.16.0.0/12 and 192.168.0.0/16 a gateway like
 *   192.168.1.1 would be routed through the proxy and break cluster traffic.
 */
function buildDefaultNoProxy(allYmlContent) {
  const parts = [
    'localhost',
    '127.0.0.1',
    '169.254.169.254',               // AWS instance metadata
    allYmlContent.pod_network_cidr  || '10.10.0.0/16',
    allYmlContent.service_cidr      || '10.96.0.0/12',
    '10.0.0.0/8',                    // AWS / on-prem 10.x.x.x nodes
    '172.16.0.0/12',                 // on-prem 172.16-31.x.x nodes
    '192.168.0.0/16',                // on-prem 192.168.x.x nodes & gateway
    '.svc',
    '.cluster.local',
  ];
  return parts.filter(Boolean).join(',');
}

/**
 * Update Ansible group_vars/all.yml with component selections
 */
function generateAnsibleVars(deployment) {
  const { selectedComponents } = deployment;
  
  // Read existing all.yml
  const projectRoot = path.resolve(__dirname, process.env.PROJECT_ROOT || '../../../');
  const allYmlPath = path.join(projectRoot, 'ansible/inventory/group_vars/all.yml');
  
  let allYmlContent = {};
  if (fs.existsSync(allYmlPath)) {
    const content = fs.readFileSync(allYmlPath, 'utf8');
    allYmlContent = yaml.load(content) || {};
  }

  // Detect OS types from individual nodes (per-node osType)
  const onPremConfig = deployment.onPremiseConfig;
  if (onPremConfig) {
    const allNodes = [
      ...(onPremConfig.controlPlane?.nodes || []),
      ...(onPremConfig.workerNodes || []).flatMap(g => g.nodes || [])
    ];
    const hasSuse = allNodes.some(n => n.osType === 'suse');
    const hasUbuntu = allNodes.some(n => n.osType !== 'suse');
    if (hasSuse && hasUbuntu) {
      allYmlContent.os_type = 'mixed';
    } else if (hasSuse) {
      allYmlContent.os_type = 'suse';
    } else {
      allYmlContent.os_type = 'ubuntu';
    }
  }

  // Add cluster-wide environment variables from config
  const envVars = deployment.clusterConfig?.envVars || deployment.onPremiseConfig?.envVars;
  if (envVars && Array.isArray(envVars) && envVars.length > 0) {
    const envObj = {};
    for (const ev of envVars) {
      if (ev.key && ev.key.trim()) {
        envObj[ev.key] = ev.value || '';
      }
    }
    if (Object.keys(envObj).length > 0) {
      allYmlContent.cluster_env_vars = envObj;
    }
  }

  // Add proxy configuration
  const proxyConfig = deployment.clusterConfig?.proxyConfig || deployment.onPremiseConfig?.proxyConfig;
  if (proxyConfig?.enabled) {
    allYmlContent.proxy_enabled = true;
    allYmlContent.HTTP_PROXY   = proxyConfig.HTTP_PROXY   || '';
    allYmlContent.http_proxy   = proxyConfig.http_proxy   || '';
    allYmlContent.HTTPS_PROXY  = proxyConfig.HTTPS_PROXY  || '';
    allYmlContent.https_proxy  = proxyConfig.https_proxy  || '';

    // If the user left NO_PROXY empty, build a safe default from the known
    // internal CIDRs so cluster-internal traffic never goes through the proxy.
    const userNoProxy = proxyConfig.NO_PROXY || proxyConfig.no_proxy || '';
    const noProxy = userNoProxy || buildDefaultNoProxy(allYmlContent);
    allYmlContent.NO_PROXY = noProxy;
    allYmlContent.no_proxy = noProxy;
  } else {
    allYmlContent.proxy_enabled = false;
    allYmlContent.HTTP_PROXY   = '';
    allYmlContent.http_proxy   = '';
    allYmlContent.HTTPS_PROXY  = '';
    allYmlContent.https_proxy  = '';
    allYmlContent.NO_PROXY     = '';
    allYmlContent.no_proxy     = '';
  }

  // Update Tyr configuration if backend-api is selected
  if (selectedComponents && selectedComponents['backend-api']) {
    if (!allYmlContent.ghcr_username) {
      allYmlContent.ghcr_username = process.env.GHCR_USERNAME || 'avivl777';
    }
    if (!allYmlContent.ghcr_password) {
      allYmlContent.ghcr_password = process.env.GHCR_PASSWORD || '';
    }
    if (!allYmlContent.tyr_version) {
      allYmlContent.tyr_version = process.env.TYR_VERSION || '1.0.7';
    }
  }

  // Update Dashboard configuration if dashboard is selected
  if (selectedComponents && selectedComponents['dashboard']) {
    if (!allYmlContent.ghcr_username) {
      allYmlContent.ghcr_username = process.env.GHCR_USERNAME || 'avivl777';
    }
    if (!allYmlContent.ghcr_password) {
      allYmlContent.ghcr_password = process.env.GHCR_PASSWORD || '';
    }
    if (!allYmlContent.dashboard_version) {
      allYmlContent.dashboard_version = process.env.DASHBOARD_VERSION || '1.0.26';
    }
  }

  return yaml.dump(allYmlContent, { indent: 2, lineWidth: -1 });
}

/**
 * Write Terraform tfvars file
 */
function writeTerraformVars(deployment, tfvarsContent) {
  const projectRoot = path.resolve(__dirname, process.env.PROJECT_ROOT || '../../../');
  const envDir = path.join(projectRoot, process.env.TERRAFORM_ENV_DIR || 'terraform/environments/aws');
  const tfvarsPath = path.join(envDir, `${deployment.clusterConfig.name}.tfvars`);
  
  // Ensure directory exists
  if (!fs.existsSync(envDir)) {
    fs.mkdirSync(envDir, { recursive: true });
  }
  
  fs.writeFileSync(tfvarsPath, tfvarsContent);
  console.log(`[ConfigGenerator] Written tfvars to: ${tfvarsPath}`);
  
  return tfvarsPath;
}

/**
 * Write Ansible variables to ansible/inventory/group_vars/all.yml.
 * Ansible resolves group_vars relative to the inventory file, so this is
 * the single location both the installer (-i inventory/<name>.ini) and
 * manual runs (-i inventory/hosts) will pick up.
 */
function writeAnsibleVars(ansibleVarsContent) {
  const projectRoot = path.resolve(__dirname, process.env.PROJECT_ROOT || '../../../');
  const inventoryGroupVarsDir = path.join(projectRoot, 'ansible/inventory/group_vars');
  const allYmlPath = path.join(inventoryGroupVarsDir, 'all.yml');

  if (!fs.existsSync(inventoryGroupVarsDir)) {
    fs.mkdirSync(inventoryGroupVarsDir, { recursive: true });
  }

  fs.writeFileSync(allYmlPath, ansibleVarsContent);
  console.log(`[ConfigGenerator] Written Ansible vars to: ${allYmlPath}`);

  return allYmlPath;
}

/**
 * Generate configuration for on-premise deployments
 */
function generateOnPremiseConfig(deployment) {
  // For on-premise, we only need Ansible vars, no Terraform
  const ansibleVarsContent = generateAnsibleVars(deployment);
  const ansibleVarsPath = writeAnsibleVars(ansibleVarsContent);
  
  return {
    ansibleVarsPath,
    ansibleVarsContent
  };
}

/**
 * Generate all configuration files for deployment
 */
function generateConfigurations(deployment) {
  const { cloudProvider } = deployment;
  
  // For on-premise deployments, skip Terraform configuration
  if (cloudProvider === 'on-premise' || cloudProvider === 'onpremise') {
    return generateOnPremiseConfig(deployment);
  }
  
  // For cloud deployments (AWS, etc.), generate both Terraform and Ansible configs
  const tfvarsContent = generateTerraformVars(deployment);
  const ansibleVarsContent = generateAnsibleVars(deployment);
  
  const tfvarsPath = writeTerraformVars(deployment, tfvarsContent);
  const ansibleVarsPath = writeAnsibleVars(ansibleVarsContent);
  
  return {
    tfvarsPath,
    ansibleVarsPath,
    tfvarsContent,
    ansibleVarsContent
  };
}

export {
  generateTerraformVars,
  generateAnsibleVars,
  writeTerraformVars,
  writeAnsibleVars,
  generateOnPremiseConfig,
  generateConfigurations
};

