import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Merge env var arrays into a single object (later sources override earlier).
 * @param {...Array<{key: string, value?: string}>} sources - Arrays of { key, value }
 * @returns {Record<string, string>}
 */
function mergeEnvVars(...sources) {
  const result = {};
  for (const source of sources) {
    if (source && Array.isArray(source)) {
      for (const ev of source) {
        if (ev.key && ev.key.trim()) {
          result[ev.key] = ev.value || '';
        }
      }
    }
  }
  return result;
}

/**
 * Generate Ansible inventory files from configuration
 * Supports both AWS (from Terraform outputs) and On-Premise (from config)
 */
class InventoryGeneratorService {
  /**
   * Generate inventory.ini content from node configuration
   */
  generateInventoryContent(config) {
    const {
      clusterName,
      controlPlane,
      workerNodes,
      ansibleUser = 'ubuntu',
      sshPrivateKeyPath  // For backward compatibility with AWS/Terraform
    } = config;

    let content = `# Ansible Inventory for ${clusterName}
# Generated by Ascendra Installer at ${new Date().toISOString()}

[all:vars]
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
`;

    // Add cluster-wide environment variables
    if (config.envVars && Array.isArray(config.envVars) && config.envVars.length > 0) {
      content += `\n# Cluster-wide environment variables\n`;
      for (const envVar of config.envVars) {
        if (envVar.key && envVar.key.trim()) {
          content += `env_${envVar.key}=${envVar.value || ''}\n`;
        }
      }
    }

    content += '\n';


    // Masters section
    content += `[masters]\n`;
    if (controlPlane && controlPlane.nodes && controlPlane.nodes.length > 0) {
      const cpSSHConfig = controlPlane.sshConfig;
      controlPlane.nodes.forEach((node, index) => {
        const hostname = node.hostname || `master-${index}`;
        content += `${hostname} ansible_host=${node.ip}`;

        // Per-node SSH override takes precedence over control plane default
        const useNodeSSH = node.sshConfig && (node.sshConfig.user || node.sshConfig.password);
        if (useNodeSSH && node.sshConfig) {
          content += ` ansible_user=${node.sshConfig.user || cpSSHConfig?.user || ansibleUser}`;
          if (node.sshConfig.password) {
            content += ` ansible_ssh_pass=${node.sshConfig.password}`;
            content += ` ansible_become_pass=${node.sshConfig.password}`;
          } else if (cpSSHConfig?.password) {
            content += ` ansible_ssh_pass=${cpSSHConfig.password}`;
            content += ` ansible_become_pass=${cpSSHConfig.password}`;
          } else if (cpSSHConfig?.privateKeyPath) {
            content += ` ansible_ssh_private_key_file=${cpSSHConfig.privateKeyPath}`;
          }
        } else if (cpSSHConfig) {
          content += ` ansible_user=${cpSSHConfig.user}`;
          if (cpSSHConfig.password) {
            content += ` ansible_ssh_pass=${cpSSHConfig.password}`;
            content += ` ansible_become_pass=${cpSSHConfig.password}`;
          } else if (cpSSHConfig.privateKeyPath) {
            content += ` ansible_ssh_private_key_file=${cpSSHConfig.privateKeyPath}`;
          }
        } else if (sshPrivateKeyPath) {
          content += ` ansible_user=${ansibleUser}`;
          content += ` ansible_ssh_private_key_file=${sshPrivateKeyPath}`;
        }

        if (node.osType) {
          content += ` node_os_type=${node.osType}`;
        }

        // Merged env: cluster + control plane + node (node overrides)
        const mergedEnv = mergeEnvVars(config.envVars, controlPlane.envVars, node.envVars);
        if (Object.keys(mergedEnv).length > 0) {
          const envJson = JSON.stringify(mergedEnv);
          content += ` node_env_vars='${envJson}'`;
        }

        content += '\n';
      });
    }

    content += '\n';

    // Workers section
    content += `[workers]\n`;
    if (workerNodes && workerNodes.length > 0) {
      workerNodes.forEach((group, groupIndex) => {
        if (group.nodes && group.nodes.length > 0) {
          const groupSSHConfig = group.sshConfig;
          
          group.nodes.forEach((node, nodeIndex) => {
            const hostname = node.hostname || `${group.groupName || 'worker'}-${nodeIndex}`;
            content += `${hostname} ansible_host=${node.ip}`;

            // Per-node SSH override takes precedence over group default
            const useNodeSSH = node.sshConfig && (node.sshConfig.user || node.sshConfig.password);
            if (useNodeSSH && node.sshConfig) {
              content += ` ansible_user=${node.sshConfig.user || groupSSHConfig?.user || ansibleUser}`;
              if (node.sshConfig.password) {
                content += ` ansible_ssh_pass=${node.sshConfig.password}`;
                content += ` ansible_become_pass=${node.sshConfig.password}`;
              } else if (groupSSHConfig?.password) {
                content += ` ansible_ssh_pass=${groupSSHConfig.password}`;
                content += ` ansible_become_pass=${groupSSHConfig.password}`;
              } else if (groupSSHConfig?.privateKeyPath) {
                content += ` ansible_ssh_private_key_file=${groupSSHConfig.privateKeyPath}`;
              }
            } else if (groupSSHConfig) {
              content += ` ansible_user=${groupSSHConfig.user}`;
              if (groupSSHConfig.password) {
                content += ` ansible_ssh_pass=${groupSSHConfig.password}`;
                content += ` ansible_become_pass=${groupSSHConfig.password}`;
              } else if (groupSSHConfig.privateKeyPath) {
                content += ` ansible_ssh_private_key_file=${groupSSHConfig.privateKeyPath}`;
              }
            } else if (sshPrivateKeyPath) {
              content += ` ansible_user=${ansibleUser}`;
              content += ` ansible_ssh_private_key_file=${sshPrivateKeyPath}`;
            }

            if (node.osType) {
              content += ` node_os_type=${node.osType}`;
            }

            // Add group labels as host variables
            if (group.labels && Object.keys(group.labels).length > 0) {
              const labelsJson = JSON.stringify(group.labels).replace(/"/g, '\\"');
              content += ` node_labels='${labelsJson}'`;
            }

            // Add group taints as host variables
            if (group.taints && group.taints.length > 0) {
              const taintsJson = JSON.stringify(group.taints).replace(/"/g, '\\"');
              content += ` node_taints='${taintsJson}'`;
            }

            // Merged env: cluster + group + node (node overrides)
            const mergedEnv = mergeEnvVars(config.envVars, group.envVars, node.envVars);
            if (Object.keys(mergedEnv).length > 0) {
              const envJson = JSON.stringify(mergedEnv);
              content += ` node_env_vars='${envJson}'`;
            }

            content += '\n';
          });
        }
      });
    }

    content += '\n';

    // Optional: Add worker groups as separate groups
    if (workerNodes && workerNodes.length > 1) {
      workerNodes.forEach((group) => {
        if (group.groupName && group.nodes && group.nodes.length > 0) {
          content += `[${group.groupName}]\n`;
          group.nodes.forEach((node, nodeIndex) => {
            const hostname = node.hostname || `${group.groupName}-${nodeIndex}`;
            content += `${hostname}\n`;
          });
          content += '\n';
        }
      });
    }

    return content;
  }

  /**
   * Generate inventory from Terraform outputs (AWS deployments)
   */
  generateFromTerraform(clusterName, terraformOutputs) {
    console.log('[InventoryGenerator] Generating inventory from Terraform outputs');

    const masterIps = terraformOutputs.master_ips?.value
      || terraformOutputs.master_public_ips?.value || [];
    const workerIps = terraformOutputs.worker_ips?.value
      || terraformOutputs.worker_public_ips?.value || [];
    const workerDetails = terraformOutputs.worker_details?.value || {};
    const sshKeyPath = terraformOutputs.ssh_private_key_path?.value;

    const config = {
      clusterName,
      sshPrivateKeyPath: sshKeyPath,
      ansibleUser: 'ubuntu',
      controlPlane: {
        nodes: masterIps.map((ip, index) => ({
          ip,
          hostname: `master-${index}`
        }))
      },
      workerNodes: []
    };

    // Group workers - for AWS we create a single group
    if (workerIps.length > 0) {
      const workerGroup = {
        groupName: 'workers',
        labels: {},
        taints: [],
        nodes: workerIps.map((ip, index) => ({
          ip,
          hostname: `worker-${index}`
        }))
      };
      config.workerNodes.push(workerGroup);
    }

    return this.generateInventoryContent(config);
  }

  /**
   * Generate inventory from on-premise configuration
   */
  generateFromOnPremise(onPremiseConfig) {
    console.log('[InventoryGenerator] Generating inventory from on-premise config');
    return this.generateInventoryContent(onPremiseConfig);
  }

  /**
   * Write inventory file to disk
   */
  writeInventoryFile(clusterName, content) {
    const projectRoot = path.resolve(__dirname, process.env.PROJECT_ROOT || '../../../');
    const inventoryDir = path.join(projectRoot, 'ansible/inventory');
    const inventoryPath = path.join(inventoryDir, `${clusterName}.ini`);

    // Ensure directory exists
    if (!fs.existsSync(inventoryDir)) {
      fs.mkdirSync(inventoryDir, { recursive: true });
    }

    // Backup existing file
    if (fs.existsSync(inventoryPath)) {
      const backupPath = `${inventoryPath}.backup-${Date.now()}`;
      fs.copyFileSync(inventoryPath, backupPath);
      console.log(`[InventoryGenerator] Backed up existing inventory to: ${backupPath}`);
    }

    // Write new inventory
    fs.writeFileSync(inventoryPath, content);
    console.log(`[InventoryGenerator] Written inventory to: ${inventoryPath}`);

    return inventoryPath;
  }

  /**
   * Generate and write inventory from Terraform outputs
   */
  createFromTerraform(clusterName, terraformOutputs) {
    const content = this.generateFromTerraform(clusterName, terraformOutputs);
    return this.writeInventoryFile(clusterName, content);
  }

  /**
   * Generate and write inventory from on-premise configuration
   */
  createFromOnPremise(onPremiseConfig) {
    const content = this.generateFromOnPremise(onPremiseConfig);
    return this.writeInventoryFile(onPremiseConfig.clusterName, content);
  }
}

export default new InventoryGeneratorService();

